Feature: integrate lidy parser
ditrit/kubernator-plugin pull request #2
Opened 2022-10-06 10:24 UTC by Zorin95670

Integrate first verson of Kubernetes parser using [Lidy](https://github.com/ditrit/lidy-js) parser.

This first version only parse simple yaml with `kind` attribute.

2022-10-06 12:40 UTC, k-y0u requested changes

2022-10-06 12:40 UTC, k-y0u commented on package.json
> +    "lidy-js": "git+https://github.com/ditrit/lidy-js.git#main"
`#main` is not the default, is it ?

2022-10-06 12:40 UTC, k-y0u commented on scripts/generate_parser.js
> +// const { preprocess } = require('lidy-js');
comments

2022-10-06 12:40 UTC, k-y0u commented on src/lidy/k8s.js
> +let rules={"main":"root","root":{"_map":{"apiVersion":"apiVersion","kind":"kind"},"_mapFacultative":{"metadata":"metadata"},"_mapOf":{"string":"string"}},"kind":"string","apiVersion":"string","metada
Ugly ! Why ?

2022-10-06 12:43 UTC, Zorin95670 commented on src/lidy/k8s.js
> +let rules={"main":"root","root":{"_map":{"apiVersion":"apiVersion","kind":"kind"},"_mapFacultative":{"metadata":"metadata"},"_mapOf":{"string":"string"}},"kind":"string","apiVersion":"string","metada
generated source

2022-10-06 12:43 UTC, Zorin95670 commented on scripts/generate_parser.js
> +// const { preprocess } = require('lidy-js');
done

2022-10-06 12:50 UTC, k-y0u approved these changes

2022-11-04 08:25 UTC, viennem approved these changes

2022-11-07 15:28 UTC, Zorin95670 commented on src/parser/KubernetesListener.js
> +   * @param {FileInformation} fileInformation - File information.
Yes, because `FileInput` extends `FileInformation` and Listener only need FileInformation so it's ok :)

2022-11-07 15:28 UTC, Zorin95670 commented on src/parser/KubernetesParser.js
> +      const listener = new KubernetesListener(input);
done

2022-11-07 15:28 UTC, Zorin95670 commented on tests/unit/parser/KubernetesParser.spec.js
> +            path: './simple.tf',
First is ok, second is not neccesary :)

2022-11-07 15:28 UTC, Zorin95670 commented on tests/unit/parser/KubernetesParser.spec.js
> +      it('Should return true on simple.tf', () => {
done

2022-11-07 16:59 UTC, viennem commented on src/parser/KubernetesListener.js
> +   * @param {FileInformation} fileInformation - File information.
ah yes, I didn't notice this!

2022-11-07 17:00 UTC, viennem approved these changes

2022-11-24 15:01 UTC, merged